# Meta Data for SEO

## Homepage
title = "Reef"
titleSeparator = "-"
titleAddition = "Reef Chain Documentation"
description = "Reef Chain is an EVM compatible chain for DeFi, NFTs and games. It is built with Parity Substrate and uses Nominated Proof of Stake consensus."

## Open Graph + Twitter Cards
images = ["reef.png"]
twitterSite = "reef_chain"
twitterCreator = "reef_chain"
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "reef.png"
schemaTwitter = "https://twitter.com/reef_chain"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/reef-defi"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "<a href=\"https://reefscan.com\">Reefscan</a> - <a href=\"https://remix.reefscan.com\">Remix</a> - <a href=\"https://console.reefscan.com\">Console</a> "

# Alert
alert = false
alertText = "Like Reef? <a class=\"alert-link\" href=\"https://github.com/reef-defi/reef-chain/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/reef-defi/reef-docs"
editPage = false
