# Meta Data for SEO

## Homepage
title = "Reef"
titleSeparator = "-"
titleAddition = "Reef Chain Documentation"
description = "Reef Chain is an EVM compatible chain for DeFi. It is built with Polkadot Substrate and uses Nominated Proof of Stake consensus."

## Open Graph + Twitter Cards
images = ["doks.png"]
twitterSite = "ReefDefi"
twitterCreator = "ReefDefi"
facebookAuthor = ""
facebookPublisher = ""
ogLocale = "en_US"

## JSON-LD
schemaType = "Organization"
schemaLogo = "logo-doks.png"
schemaTwitter = "https://twitter.com/ReefDeFi"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/reef-defi"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"

# Footer
footer = "Website - Block Explorer - GitHub"

# Alert
alert = false
alertText = "Like Reef? <a class=\"alert-link\" href=\"https://github.com/reef-defi/reef-chain/stargazers\">Star on GitHub</a>. Thanks!</a>"

# Edit Page
docsRepo = "https://github.com/reef-defi/reef-docs"
editPage = false
